### ISSUE TITLE
theory_parser_literals

### ISSUE THREAD

**Issue by jorgefandinno** [jorgefandinno/eclingo#16]
Replace the use of 
```
eclingo.parsing.transformers.theory_parser_literals.theory_term_to_literal()
```
by
```
clingox.ast.theory_term_to_literal()
```

This function is not yet available in the release version of ```clingox```, so we will use the develop version. Branch ```theory_term_to_literal``` has been already configured to use this version. Create a new new branch from this branch.

Start by running the test to be sure that the configuration is working correctly.

The documentation of ```clingox.ast.theory_term_to_literal()``` is not yet available in the web. The documentation is in the docstring of the code https://github.com/potassco/python-clingox/blob/5b096ce71e2198252bf2552641d726b950f58eb2/clingox/ast.py#L1289. It should be possible to use the function by reading only the docstring (without the code). If it not the case, then let me know so we update the docstring as necessary.

**Comment by lute47lillo** [comment]
I have replace the use, however I've found some issues:

When calling:
https://github.com/potassco/python-clingox/blob/5b096ce71e2198252bf2552641d726b950f58eb2/clingox/ast.py#L1289-L1305

it makes a call to -> **return _theory_term_to_literal(x, True, ast.Sign.NoSign)**

Inside that function, the if statement -->     **if x.ast_type == ASTType.TheoryFunction:**

and the elif counterpart -->     
**elif (
        x.ast_type == ASTType.SymbolicTerm
        and x.symbol.type == clingo.SymbolType.Function
        and x.symbol.name
    )**

are never evaluated to _True_
Therefore raising the RunTimeError -->     **raise RuntimeError(f"{location_to_str(x.location)}: invalid literal `{x}`")**

BUT, the problem is that:  **AttributeError: no attribute: location** 
So, I've been trying to backtrack the issue, either because the atom is never built by the buil_atom function and the attribute of location is not assigned OR it is because the **x = clingo_literal_parser()(x)** call that occurs on line 1304.

I'll look more onto it, but I'll drop this here for you to take a look into it too
