### ISSUE TITLE
Move the test folder

### ISSUE THREAD

**Issue by jorgefandinno** [jorgefandinno/eclingo#3]
Move the test folder inside the eclingo folder and correct the necessary paths

**Comment by lute47lillo** [comment]
I've moved the test folder inside the eclingo folder and fixed the path for the functions test_yale_g94, test_eligible_g94 and test_prog_g94 by going up one parent directory on the app_path, since that was failing once moving the tests folder.

https://github.com/jorgefandinno/eclingo/blob/bc798dd9071315d06c6e5a492f868ce57630f115/eclingo/tests/test_app.py#L105-L106

All the tests are passed now, but I don't know if this fix that I just did was because how I have setup my local working directory, so it'll be good if you can clone this branch and test it too maybe.

My cwd is ../lute_eclingo/eclingo/eclingo.....

Where lute_eclingo is just a folder I created on my Desktop where I cloned the repo and it starts on the first eclingo
