### ISSUE TITLE
show bug?

### ISSUE THREAD

**Issue by jorgefandinno** [jorgefandinno/eclingo#65]
Any idea why ```&k{a}``` is not shown in the following program:
```bash
fandinno@IST-jfandinno:~/student-research/eclingo (reification)
$echo "a. #show a/0." | eclingo 0
Solving...
World view: 1

SATISFIABLE
```

**Comment by lute47lillo** [comment]
@jorgefandinno That's certainly interesting because a program just of "a." will not show a world view either.

**Comment by jorgefandinno** [comment]
> @jorgefandinno That's certainly interesting because I'm getting UNSATISFIABLE. However, is it not right? A program such as "a." should yield the empty world view right?
> 
> 

Yes. When you add the show, it should print "&k{a}"

**Comment by jorgefandinno** [comment]
In branch ```reification``` works as I said before. In branch ```lute/add_output_options``` shows ```UNSATISFIABLE``` as you say.

```bash
fandinno@IST-jfandinno:~/student-research/eclingo (reification)
$echo "a. #show a/0." | eclingo 0
Solving...
World view: 1

SATISFIABLE
```

```bash
fandinno@IST-jfandinno:~/student-research/eclingo (lute/add_output_options)
$eclingo a.lp 0
Solving...
World view: 1

UNSATISFIABLE
```

The expected behaviour is
```bash
$echo "a. #show a/0." | eclingo 0
Solving...
World view: 1
&k{a}
SATISFIABLE
```

**Comment by lute47lillo** [comment]
> In branch `reification` works as I said before. In branch `lute/add_output_options` it used to show`UNSATISFIABLE` as you say. That is fixed now. Still, both get
> 
> ```shell
> fandinno@IST-jfandinno:~/student-research/eclingo (reification)
> $echo "a. #show a/0." | eclingo 0
> Solving...
> World view: 1
> 
> SATISFIABLE
> ```
> 
> The expected behaviour is
> 
> ```shell
> $echo "a. #show a/0." | eclingo 0
> Solving...
> World view: 1
> &k{a}
> SATISFIABLE
> ```

Let me look into it. I think is part of the meta-programming when creates the show_statement facts.

**Comment by jorgefandinno** [comment]
Another example:

```bash
$echo "a :- not &k{ not a}. #show a/0." | eclingo 0
Solving...
World view: 1
&m{a}
World view: 2

SATISFIABLE
```

works as without shows. The first world view should be ```&k{a}```

**Comment by lute47lillo** [comment]
> > In branch `reification` works as I said before. In branch `lute/add_output_options` it used to show`UNSATISFIABLE` as you say. That is fixed now. Still, both get
> > ```shell
> > fandinno@IST-jfandinno:~/student-research/eclingo (reification)
> > $echo "a. #show a/0." | eclingo 0
> > Solving...
> > World view: 1
> > 
> > SATISFIABLE
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The expected behaviour is
> > ```shell
> > $echo "a. #show a/0." | eclingo 0
> > Solving...
> > World view: 1
> > &k{a}
> > SATISFIABLE
> > ```
> 
> Let me look into it. I think is part of the meta-programming when creates the show_statement facts.

@jorgefandinno I have found the issue, there are a couple ways of dealing with it. Explanation here:

So if we do 
```shell
$echo "a. #show a/0." | eclingo 0
```
The reified program is: 
`tag(incremental). atom_tuple(0). atom_tuple(0,1). literal_tuple(0). rule(disjunction(0),normal(0)). atom_tuple(1). atom_tuple(1,2). rule(disjunction(1),normal(0)). output(u(a),0). output(show_statement(a),0).`

Now, based on the base meta program of the generator, it will only create candidates for:
`positive_candidate(k(A)) :- output(k(A), B), conjunction(B).`
 `negative_candidate(k(A)) :- output(k(A), B), not conjunction(B).`

So, there will not be any candidate generated. We need to create a new rule that accounts for single atom-facts like saying:
```shell
a. #show a/0.
or 
b. #show b/0.
```

Because, those do not generate output(k(a),_) but instead output(u(a),_) and that later spirals into the WorldView builder that checks for both show_statement facts and the candidates to generate the right world views.

Another option will be to yield the world view ANYTIME show_statement(X) appears, but then since we are checking against the tested candidates in the current implementation I can see that providing some issues.

**Comment by lute47lillo** [comment]
> I am looking at `WorldWiewBuilderReificationWithShow` and I got confused. I was expecting to that a program similar to the one in the tester was added to the control object. Instead, I only see
> 
> https://github.com/jorgefandinno/eclingo/blob/14ebae9c6a6429996c2b38c81b28ab28245871e3/src/eclingo/solver/world_view_builder.py#L108-L113
> 
> Am I missing something?
> 
> Can this be the source of the problem?

Not really, that is the minimum meta-programming you need in order to generate enought show_statements. As I said before, the issue comes from not generating candidates on the generator.

Since the program "a." does not generate candidates, including #show a/0. will still not create the world view, because in order to create the world view it checks for the candidates, and the show_statement fact, if the overlap, then the Wview is created. 

In this case, only the show_statement is being created.

**Comment by jorgefandinno** [comment]
There is something strange here. The candidate only carries information about epistemic literals that occur in the program, not about the ones that need to be shown. To obtain that information, we need to compute the cautions consequences again. 

Where is that done?

For instance, for
```
{a}.
:- not a.
b :- &k{a}.
#show b/0.
```
we should get "&k{b}" but that information is not in the candidate.

**Comment by lute47lillo** [comment]
> There is something strange here. The candidate only carries information about epistemic literals that occur in the program, not about the ones that need to be shown. To obtain that information, we need to compute the cautions consequences again.
> 
> Where is that done?
> 
> For instance, for
> 
> ```
> {a}.
> :- not a.
> b :- &k{a}.
> #show b/0.
> ```
> 
> we should get "&k{b}" but that information is not in the candidate.

I don't think I follow you there. Shouldn't the show only yield a Wview with such #show X/0. if that X appears as part of the world models?

**Comment by jorgefandinno** [comment]
No, &k{X} should if there is a show for X and it is a cautions consequence of the program when all epistemic literals are assumed as in the candidate.

**Comment by lute47lillo** [comment]
> No, &k{X} should if there is a show for X and it is a cautions consequence of the program when all epistemic literals are assumed as in the candidate that was tested as a world view.

So, there has to be a rule such as: 

> {a}.
> :- not a.
> b :- &k{a}.
> #show b/0.

The cautious consequences are set in Tester in one hand. 

On the other, does it mean, that in this case we also need to include another rule in the meta-progam that relates show_statement(b), and output(k(u(a)) to check if there is a rule that relates b to k{a}?

**Comment by jorgefandinno** [comment]
The world view builder has to compute the cautious consequences. If b is a
cautious consequence and is in a show, it should print &k{b}

**Comment by lute47lillo** [comment]
I believe this issue has been addressed with the last Lute/fixing branches merge into reification.
